# Server Configuration
server.port=8080

# Application Name
spring.application.name=bad-product-service

# Logging Configuration
logging.level.com.cs6650.product=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Service Error Configuration
product.service.error-rate=0.5
